// Credit: adapted from Zulip discussion https://15-472-s26.zulipchat.com/#narrow/channel/570157-A2/topic/Adding.20Cube.20Utility.20to.20Maekfile/with/575174040
// Also learned from https://learnopengl.com/Guest-Articles/2022/Compute-Shaders/Introduction

#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in; // defining the size of the local invocations per dimension in the compute shader

// std140: a memory layout rule for Uniform Buffer Object. It defines how the GPU packs struct fields in memory so the CPU and GPU agree on where each field sits. Without it, the GPU might pad/align fields differently for the C++ struct.
// Other option: std430 — tighter packing (no vec3 padding quirks), but not allowed for UBOs in older GLSL, only for SSBOs.
// UBO: a GPU buffer that holds read-only data that the shader reads uniformly, — meaning every invocation reads the same value (as opposed to storage images/buffers where each invocation reads/writes different pixels)
layout(set=0, binding=0, std140) uniform Inface {
    mat3x3 WORLD_FROM_IN_PX;
};
layout(set=0, binding=1) uniform sampler2D inFace; // changed from image2D to sampler2D to denoise.

layout(set=1, binding=0, std140) uniform OutFace {
    mat3x3 WORLD_FROM_OUT_PX;
};
layout(set=1, binding=1, rgba32f) uniform restrict image2D outFace;

const float PI = 3.14159265358979323846;

#ifdef GGX
layout(set=2, binding=0, std140) uniform Roughness { // use std140: uniform blocks have a standard cross-platform cross-vendor layout. Unused uniforms will not be eliminated. Credit: https://stackoverflow.com/questions/16270846/when-should-i-use-std140-in-opengl
    float roughness;
};

// Credit: https://learnopengl.com/PBR/IBL/Specular-IBL, https://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf
vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float Roughness) {
    // Note that Epic Games uses the squared roughness for better visual results as based on Disney's original PBR research.
    float a = Roughness * Roughness;

    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);

    // from spherical coordinates to cartesian coordinates (tangent space)
    vec3 H;
    H.x = cos(phi) * sinTheta;
    H.y = sin(phi) * sinTheta;
    H.z = cosTheta;

    // from tangent-space vector to world-space sample vector
    vec3 up        = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent   = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);

    vec3 sampleVec = tangent * H.x + bitangent * H.y + N * H.z;
    return normalize(sampleVec);
}

// Credit: https://holger.dammertz.org/stuff/notes_HammersleyOnHemisphere.html
// Generates a quasi-random low-discrepancy value in [0,1) by bit-reversing i.
float RadicalInverse_VdC(uint bits) {
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10; // / 0x100000000
}

// Returns the i-th point in the Hammersley 2D low-discrepancy sequence over N total samples.
vec2 Hammersley(uint i, uint N) {
    return vec2(float(i)/float(N), RadicalInverse_VdC(i));
}

// Credit: Direct lighting from https://learnopengl.com/PBR/Lighting
float DistributionGGX(float NdotH, float Roughness) {
    float a  = Roughness * Roughness;
    float a2 = a * a;
    float NdotH2 = NdotH * NdotH;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;
    return a2 / denom;
}
#endif

void main() {
    /*
    uvec3 gl_GlobalInvocationID = global index of the current work item = (gl_WorkGroupID * gl_WorkGroupSize + gl_LocalInvocationID)
    - uvec3 gl_LocalInvocationID = index of the current work item in the work group
    - unvec3 gl_WorkGroupID and uvec3 gl_WorkGroupSize = index and size of of the work group (local size) operated on defined with layout
    The user can use a concept called work groups to define the space the compute shader is operating on. Work Groups are the smallest amount of compute operations that the user can execute
    */
    ivec2 outCoord = ivec2(gl_GlobalInvocationID.xy); // this answers: which output pixel is this code responsible for?

    // imageSize: retrieve the dimensions of an image. Returns ivec2 for 2D image. https://registry.khronos.org/OpenGL-Refpages/gl4/html/imageSize.xhtml
    ivec2 outSize = imageSize(outFace);
    ivec2 inSize = textureSize(inFace, 0);

    if (outCoord.x >= outSize.x || outCoord.y >= outSize.y) return; // Valid pixel coordinates are 0 to outSize.x - 1

    // pixel (px, py)  -> multiply by WORLD_FROM_PX  -> world-space direction vector
    vec3 n = normalize(WORLD_FROM_OUT_PX * vec3(float(outCoord.x), float(outCoord.y), 1.0));

    #ifdef LAMBERTIAN
    /*
    emitted light = integrate over all incoming radiance
    accumulate contribution from every pixel of this inFace
    to build up the irradiance at surface normal n
    i.e. the total light arriving at a surface patch facing direction n
    */
    vec3 acc = vec3(0.0);

    //                    Li(ωi) = incoming radiance from direction ωi = color stored in the input cubemap face at pixel(x, y)
    //                             max(n·ωi, 0) attenuates light coming from behind the surface, where the dot product is negative
    //                                              dΩ weights each light sample by how much of
    // irradiance(n) = Σ  Li(ωi) · max(n · ωi, 0) · dΩ(ωi)
    //                 {all input pixels}

    // Credit: Prof Jim's texel-area.js from https://15-472-s26.zulipchat.com/#narrow/channel/570157-A2/topic/More.20on.20Texel.20Areas/with/575171358
    float area = (4.0 / float(inSize.x * inSize.x)); // one pixel of area on the cube surface; the cube face spans [-1, 1] × [-1, 1], total area = 4
    for (int y = 0; y < inSize.y; y++) {
        for (int x = 0; x < inSize.x; x++) {
            // calculates how much radiance from direction in_dir reaches the surface facing n

            // imageLoad: load a single texel from an image. https://registry.khronos.org/OpenGL-Refpages/gl4/html/imageLoad.xhtml
            vec3 Li = texelFetch(inFace, ivec2(x, y), 0).rgb;

            // WORLD_FROM_IN_PX does: (px, py, 1) -> world_dir_unnormalized
            vec3 in_dir = WORLD_FROM_IN_PX * vec3(float(x), float(y), 1.0); // not normalized yet
            float cos_theta = max(0.0, dot(n, normalize(in_dir)));

            float s = (float(x) + 0.5) / float(inSize.x) * 2 - 1;
            float t = (float(y) + 0.5) / float(inSize.y) * 2 - 1;
            // z = 1 implicitly (face plane)
            float face_dist_sq = s*s + t*t + 1.0; // = x2 + y2 + z2 = squared dist from the origin to the point (s, t, u), u = 1 (face sits on plane with depth = 1) on the cube face plane

            float dir_omega = area * pow(face_dist_sq, -1.5); // dΩ(ωi)

            acc += Li * cos_theta * dir_omega;
        }
    }

    // vec3 acc = imageLoad(inFace, outCoord).rgb; // test: copy in -> out
    vec3 prevAcc = imageLoad(outFace, outCoord).rgb;

    // The imageStore function takes:
    // - the image unit to write to as first argument,
    // - the absolute texel coordinate as second argument, and
    // - the data value to store at this texel as third.
    imageStore(outFace, outCoord, vec4((acc / PI) + prevAcc, 0.0)); // acc is for current face, prevAcc is for all prev faces
    #endif

    #ifdef GGX
    /*
    Instead of uniformly or randomly (Monte Carlo) generating sample vectors over the integral's hemisphere, 
    we'll generate sample vectors biased towards the general reflection orientation of the microsurface halfway vector based on the surface's roughness.
    Process: begin a large loop, generate a random (low-discrepancy) sequence value, take the sequence value to generate a sample vector in tangent space, transform to world space, and sample the scene's radiance
    */

    vec3 N = n; // output pixel direction
    vec3 V = n; // split-sum approximation: view = reflection = normal

    vec3 prefiltered_color  = vec3(0.0);
    float total_weight = 0.0;

    const uint SAMPLE_COUNT = 1024u;
    mat3x3 IN_PX_FROM_WORLD = inverse(WORLD_FROM_IN_PX);

    for (uint i = 0u; i < SAMPLE_COUNT; i++) {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H  = ImportanceSampleGGX(Xi, N, roughness);
        float NdotH = clamp(dot(N, H), 0.0, 1.0);
        float HdotV = clamp(dot(H, V), 0.0, 1.0);

        // Credit: Bright dots in the pre-filter convolution from https://learnopengl.com/PBR/IBL/Specular-IBL
        float D   = DistributionGGX(NdotH, roughness);
        float pdf = (D * NdotH / (4.0 * HdotV)) + 0.0001;
        float resolution = float(inSize.x); // resolution of source cubemap (per face)
        float saTexel  = 4.0 * PI / (6.0 * resolution * resolution); // how much solid angle one source cubemap texel covers
        float saSample = 1.0 / (float(SAMPLE_COUNT) * pdf + 0.0001); // how much solid angle this Monte Carlo sample covers
        // If one sample covers a bigger area than one texel, you should sample a blurrier mip.
        float mipLevel = roughness == 0.0 ? 0.0 : 0.5 * log2(saSample / saTexel);

        vec3 L  = normalize(2.0 * dot(V, H) * H - V);

        float NdotL = clamp(dot(N, L), 0.0, 1.0);
        if (NdotL > 0.0) {
            // logic equivalent for: textureLod(envMap, L, mipLevel).rgb
            vec3 in_dir = IN_PX_FROM_WORLD * L; // WORLD_FROMIN_PX_FROM_WORLD_IN_PX does: world_dir_unnormalized -> (px * k, py * k, 1 * k)
            if (in_dir.z <= 0) continue; // dir is behind the face
            float px_float = in_dir.x / in_dir.z;
            float py_float = in_dir.y / in_dir.z;
            if (px_float < 0.0 || px_float >= float(inSize.x) || py_float < 0.0 || py_float >= float(inSize.y)) continue; // does not hit current face
            vec2 uv = vec2(px_float / float(inSize.x), py_float / float(inSize.y));
            // textureLod: perform a texture lookup with explicit level-of-detail. Credit: https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureLod.xhtml
            vec3 Li = textureLod(inFace, uv, mipLevel).rgb;

            prefiltered_color += Li * NdotL; // radiance from inFace
            total_weight += NdotL; // samples with less influence on the final result (for small NdotL) contribute less to the final weight
        }
    }

    // output: prefiltered_color = what color light comes from a certain direction at a certain roughness?
    // main-cube.cpp divides rgb / alpha at readback to produce the final normalized color.
    vec4 prev = imageLoad(outFace, outCoord);
    imageStore(outFace, outCoord, vec4(prefiltered_color + prev.rgb, total_weight + prev.a));
    #endif
}
